server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quizdb

telegram:
  name: TestingQuestionBot
  token: 1472903954:AAFadlgfjWIV0EVmJDL6FHWnmRsX7wHVpWo