server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quizdb

telegram:
  name: ${{BOT_NAME}}
  token: ${{BOT_TOKEN}}